config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :places
  devise_for :users
  resources :friendships
  get 'users/search' => 'users#search'
  resources :users

  post 'teams/:id/add' => 'teams#addmember'

  get 'teams/:id/add' => 'teams#add'
  get 'users/:user_id/activities' => 'activities#index'
  get 'activities/leaderboards' => 'activities#leaderboards'
  resources :activities

  root 'dashboard#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController


  def index
    @teams = current_user.teams.where(captain_id: current_user.id)
    @activities = []
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_activities_list.html.erb
<% activities.each do |activity| %>
    <% attributes = ActiveSupport::JSON.decode(activity.acattributes) %>
    <% adate = activity.date %>
    <h2>
      <%= activity.actype %>
      at <%= link_to activity.place.name, activity.place, class: "std-link" %>
    </h2>

    <h4>
      <% if (adate - Time.now).to_i/86400 > 7 || (adate - Time.now) < 0 %>
          <%= adate.day %> of <%= adate.strftime("%B") %> <%= adate.year %> by <%= adate.hour.to_s.rjust(2, '0') %>:<%= adate.min.to_s.rjust(2, '0') %>
      <% else %>
          This <%= adate.strftime("%A") %> by <%= adate.hour.to_s.rjust(2, '0') %>:<%= adate.min.to_s.rjust(2, '0') %>
      <% end %>
    </h4>

    <p>
      <strong>Duration:</strong>
      <% if activity.duration.nil? %>
          Currently unknown
      <% else %>
          <%= seconds_to_time(activity.duration) %>
      <% end %>
    </p>

    <% if activity.Swimming? %>
        <p>
          <strong>Pools:</strong>
          <% if attributes['pools'].nil? || attributes['pools'] == 0 || attributes['pools'] == '' %>
              Not even one...
          <% else %>
              <%= attributes['pools'] %>
          <% end %>
        </p>
    <% elsif activity.Running? || activity.Cycling? %>
        <p>
          <strong>Speed:</strong>
          <%= attributes['speed'] %> Km/h
        </p>
        <p>
          <strong>Distance:</strong>
          <%= attributes['distance'] %> meters
        </p>
    <% elsif activity.Gymn? %>
        <p>
          <strong>Sets:</strong>
          <%= attributes['sets'] %>
        </p>
    <% end %>
<% end %>

app/views/dashboard/index.html.erb
<div id="dash-b1">
  <div>
    <div id="dash-calendar-box" class="calendar" data-user-id="<%= current_user.id %>"></div>
  </div
  ><div>
    <div id="own-teams-container" class="stripped-list">
      <h2>Your Teams</h2>
      <ul>
        <% if @teams.count == 0 %>
          <li class="empty-list">
            <h5>
              You have no teams
            </h5>
            <%= link_to 'Create a Team', new_team_path, remote:true, class: "std-btn-link" %>
          </li>
        <% else %>
          <% @teams.each do |team| %>
                <li class="team-box">
                  <%= link_to(team, class: "team-small-image") do %><% end %>
                  <div class="team-small-info">
                    <%= link_to(team, class: "team-name std-link") do %>
                        <%= team.name %>
                    <% end %>
                    <div><strong><%= team.users.count %></strong> members</div>
                    <div class="team-small-links std-links">
                      <%= link_to 'Disband this team', team, method: :delete, data: {confirm: 'Are you sure?'}, class: "" %>
                    </div>
                  </div>
                </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div id="dash-b2">
  <div id="dash-friends-container" class="stripped-list">
    <h2>Your Friends</h2>
    <h5>What have they been up to?</h5>
    <div class="list">
      <% friends = get_friends(current_user) %>
      <% if friends.count > 0 %>
          <% friends.each do |friend| %>
            <%= link_to(activities_path(:user_id => friend.id), remote: true, class: 'friend-box') do %>
                <div class="friend-small-image"></div>
                <div class="friend-small-info">
                  <div class="friend-name"><%= friend.name %></div>
                  <div><strong><%= friend.activities.count %></strong> activities</div>
                </div>
            <% end %>
          <% end %>
      <% end %>
    </div>
  </div
  ><div id="dash-friend-act-display">
    <%= render partial: 'activities_list', locals: { activities: @activities} %>
  </div>
</div>