config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :places
  devise_for :users
  resources :friendships
  get 'users/search' => 'users#search'
  resources :users

  post 'teams/:id/add' => 'teams#addmember'

  get 'teams/:id/add' => 'teams#add'
  get 'users/:user_id/activities' => 'activities#index'
  get 'activities/leaderboards' => 'activities#leaderboards'
  resources :activities

  root 'dashboard#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
  has_and_belongs_to_many :teams

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  def self.search(search, current_user)
    search_condition = "%" + search + "%"
    User.where("name LIKE (?)","%#{search_condition}%").where("id != #{current_user.id}")
    #find(:all, :conditions => [search_condition, search_condition])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    respond_to do |format|
      format.html
      format.xml {render :xml => @user}
    end
  end

  def search
    if params[:search].nil?
      @users = nil
    else
      @users = User.search(params[:search], current_user)
    end
  end

  def edit
  end

  def update
    userParams = user_params
    name = userParams['name'].split(' ').map {|f| f.capitalize}
    @user.name = name.join(' ')
    @user.age = userParams['age'].to_i
    @user.sex = userParams['sex']
    @user.save!
    redirect_to @user
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age, :sex)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name, class: "std-label" %><br>
      <%= f.text_field :name, class: "std-field" %>
    </div>
    <div class="field">
      <%= f.label :age, class: "std-label" %><br>
      <%= f.number_field :age, class: "std-field" %>
    </div>
    <div class="field">
      <%= f.label :gender, class: "std-label" %><br>
      <%= f.radio_button  :sex,"Female", checked: @user.sex? %><%= f.label :sex, "Female", class: 'sex' %>
      <%= f.radio_button  :sex,"X", checked: @user.sex?, class: 'sex'%> <%= f.label :sex, "X", class: 'sex' %>
      <%= f.radio_button  :sex,"Male", checked: @user.sex?, class: 'sex' %> <%= f.label :sex, "Male", class: 'sex' %>
    </div>
    <div class="actions">
      <%= f.submit class: "std-btn" %>
    </div>
<% end %>

app/views/users/_search_form.html.erb
<%= form_tag({:controller => 'users', :action => 'search'}, :method => 'get') do %>
    <%= text_field_tag :search, params[:search], :id => 'search_field', class: 'std-field' %>
    <%= submit_tag "Search", :name => nil, class: 'std-btn' %>
<% end %>

app/views/users/_show_other.html.erb
<div id="upper-row">
  <div id="image-col">
    <div id="user-profile-image"></div>
  </div>
  <div id="info-col">
    <div>
      <div id="name" class="user-info-p"><%= @user.name %></div>
      <div id="email"><strong>Email: </strong><%= @user.email %></div>
      <div id="age">
        <strong>Age: </strong>
        <% if @user.age.nil? %>
            Not shown
        <% else %>
            <%= @user.age %>
        <% end %>
      </div>
      <div id="sex"><strong>Gender: </strong>
        <% if @user.sex.nil? %>
            Not shown
        <% else %>
            <%= @user.sex %>
        <% end %>
      </div>
      <% friends_accepted = current_user.friends.merge(Friendship.accepted) + current_user.inverse_friends.merge(Friendship.accepted)%>
      <% friends_pending = current_user.friends.merge(Friendship.pending) + current_user.inverse_friends.merge(Friendship.pending)%>
      <% if !friends_accepted.include?(@user) && !friends_pending.include?(@user) %>
          <%= form_for(Friendship.new) do |f| %>
              <%= f.hidden_field :friend_id, value: @user.id %>
              <%= f.submit "Send friend request", class: 'std-btn' %>
          <% end %>
      <% elsif friends_pending.include?(@user) %>
              You already asked this person to be your friend... be patient!
      <% else %>
            You are friends with <%= @user.name %>
      <% end %>
    </div>
  </div>
</div>
<div id="lower-row">
  <div id="calendar-box" class="calendar" data-user-id="<%= current_user.id %>"></div>
  <div id="user-lists-box">
    <div class="tabs">
      <ul class="tab-links">
        <li class="active"><a href="#tab1">Activities</a></li>
        <li><a href="#tab2">Teams</a></li>
        <li><a href="#tab3">Friends</a></li>
      </ul>
      <div class="tab-content">
        <div id="tab1" class="tab active">
          <div id="select-wrapper">
            <select id="activity-type-select" name="activity type">
              <option value="all">All</option>
              <option value="swimming">Swimming</option>
              <option value="running">Running</option>
              <option value="gym">Gym</option>
              <option value="cycling">Cycling</option>
            </select>
          </div>
          <% if @user.activities.count == 0 %>
              <div class="tab-header"><%= @user.name %> doesn't work out much...</div>
          <% else %>
              <% @user.activities.each do |activity| %>
                  <div class="activity-box">
                    <%= link_to(activity, class: "activity-small-image") do %><% end %>
                    <div class="activity-small-info">
                      <div><%= activity.date %></div>
                      <div><%= activity.actype %></div>
                      <div><%= activity.place.name %></div>
                      <div class="activity-small-links std-links">
                      </div>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>
        <div id="tab2" class="tab">
          <% if @user.teams.count == 0 %>
              <div class="tab-header"><%= @user.name %> doesn't belong to any team</div>
          <% else %>
              <div class="tab-header"><%= @user.teams.count %> team(s)</div>
              <% @user.teams.each do |team| %>
                  <div class="team-box">
                    <%= link_to(team, class: "team-small-image") do %><% end %>
                    <div class="team-small-info">
                      <%= link_to(team, class: "team-name std-link") do %>
                          <%= team.name %>
                      <% end %>
                      <% if team.captain_id == current_user.id %>
                          <div>You are the leader</div>
                      <% else %>
                          <div><%= link_to team.captain.name, action: 'show', id: team.captain_id %> is the leader</div>
                      <% end %>
                      <div><strong><%= team.users.count %></strong> members</div>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>
        <div id="tab3" class="tab">
          <% friends = get_friends(@user) %>
          <% if friends.count == 0 %>
              <div class="tab-header"><%= @user.name %> seems quite the lonely one</div>
          <% else %>
                  <div class="tab-header"><%= friends.count %> friend(s)</div>
              <% friends.each do |friend| %>
                  <div class="friend-box">
                    <%= link_to(friend, class: "friend-small-image") do %><% end %>
                    <div class="friend-small-info">
                      <%= link_to(friend, class: "friend-name std-link") do %>
                          <%= friend.name %>
                      <% end %>
                      <div><strong><%= friend.activities.count %></strong> activities</div>
                      <div class="friend-small-links std-links">
                      </div>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_show_self.html.erb
<div id="upper-row">
  <div id="image-col">
    <div id="user-profile-image"></div>
  </div>
  <div id="info-col">
    <div>
      <div id="name" class="user-info-p"><%= @user.name %><a class="icon-pencil" id="edit-profile-pencil" href="<%= edit_user_path %>" title="Edit Information"  style="vertical-align:middle"></a> </div>
      <div id="email"><strong>Email: </strong><%= @user.email %></div>
      <div id="age" >
        <strong>Age: </strong>
        <% if @user.age.nil? %>
            Not shown
        <% else %>
            <%= @user.age %>
        <% end %>
      </div>
      <div id="sex" class="user-info-line"><strong>Gender: </strong>
        <% if @user.sex.nil? %>
            Not shown
        <% else %>
            <%= @user.sex %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="lower-row">
  <div id="calendar-box" class="calendar" data-user-id="<%= current_user.id %>"></div>
  <div id="user-lists-box">
    <div class="tabs">
      <ul class="tab-links">
        <li class="<%= "active" if flash[:tab].nil? or flash[:tab]=="Activities"  %>"><a href="#tab1">Activities</a></li>
        <li class="<%= "active" if flash[:tab]=="Teams"  %>"><a href="#tab2">Teams</a></li>
        <li class="<%= "active" if flash[:tab]=="Friends"  %>"><a href="#tab3">Friends</a></li>
      </ul>
      <div class="tab-content">
        <div id="tab1" class="tab <%= "active" if flash[:tab].nil? or flash[:tab]=="Activities"  %>">
          <div id="select-wrapper">
            <select id="activity-type-select" name="activity type">
              <option value="all">All</option>
              <option value="swimming">Swimming</option>
              <option value="running">Running</option>
              <option value="gym">Gym</option>
              <option value="cycling">Cycling</option>
            </select>
          </div>
          <% if @user.activities.count == 0 %>
              <div class="tab-header">You don't seem to work out much...</div>
          <% else %>
              <% @user.activities.each do |activity| %>
                  <div class="activity-box">
                    <%= link_to(activity, class: "activity-small-image") do %><% end %>
                    <div class="activity-small-info">
                      <div>
                        <%= activity.date %>
                      </div>
                      <div><%= activity.actype %></div>
                      <div><%= activity.place.name %></div>
                      <div class="activity-small-links std-links">
                        <a class="icon-pencil" id="edit-ownActivity-image" data-remote="true" href="<%=  edit_activity_path(activity) %>" title="Edit Activity"  style="vertical-align:middle"></a>
                        <a class="icon-scratch" id="remove-ownActivity-scratch" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href="<%= activity_path(activity) %>" title="Remove Activity"  style="vertical-align:middle"></a>
                      </div>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>

        <div id="tab2" class="tab <%= "active" if flash[:tab]=="Teams" %>">
          <% if @user.teams.count == 0 %>
              <div class="tab-header">You don't have a team</div>
          <% else %>
              <div class="tab-header"><%= @user.teams.count %> team(s)</div>
              <% @user.teams.each do |team| %>
                  <div class="team-box">
                    <%= link_to(team, class: "team-small-image") do %><% end %>
                    <div class="team-small-info">
                      <%= link_to(team, class: "team-name std-link") do %>
                          <%= team.name %>
                      <% end %>
                      <% if team.captain_id == current_user.id %>
                          <div>You are the leader</div>
                      <% else %>
                          <div><%= link_to team.captain.name, action: 'show', id: team.captain_id %> is the leader</div>
                      <% end %>
                      <div><strong><%= team.users.count %></strong> members</div>
                      <div class="team-small-links std-links"></div>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>

         <div id="tab3" class="tab <%= "active" if flash[:tab]=="Friends" %>">
           <% friendships = get_friendships(current_user) %>
          <% if friendships.count == 0 %>
              <div class="tab-header">You have no friends</div>
          <% else %>
              <div class="tab-header"><%= friendships.count %> friend(s)</div>
              <% friendships.each do |friendship| %>
                  <% friend = User.find(friendship.friend_id) %>
                  <% if friend.id == current_user.id %>
                      <% friend = User.find(friendship.user_id) %>
                  <% end %>
                  <div class="friend-box">
                    <%= link_to(friend, class: "friend-small-image") do %><% end %>
                    <div class="friend-small-info">
                      <%= link_to(friend, class: "friend-name std-link") do %>
                          <%= friend.name %>
                      <% end %>
                      <div><strong><%= friend.activities.count %></strong> activities</div>
                      <div class="friend-small-links std-links">
                        <a class="icon-scratch" id="remove-ownFriend-scratch" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href="<%= friendship_path(friendship) %>" title="Remove Friend"  style="vertical-align:middle"></a>
                      </div>
                    </div>
                  </div>
              <% end %>
          <% end %>
          <div class="friends-divisory"></div>
          <% if @user.inverse_friendships.merge(Friendship.pending).count == 0 %>
              <div class="tab-header">You have no pending invitations</div>
          <% else %>
              <div class="tab-header"><%= @user.inverse_friendships.merge(Friendship.pending).count %> pending invitations</div>
              <% @user.inverse_friendships.merge(Friendship.pending).each do |friendship| %>
                  <% friend = User.find(friendship.user_id) %>
                  <div class="friend-box">
                    <%= link_to(friend, class: "friend-small-image") do %><% end %>
                    <div class="friend-small-info">
                      <%= link_to(friend, class: "friend-name std-link") do %>
                          <%= friend.name %>
                      <% end %>
                      <div><strong><%= friend.activities.count %></strong> activities</div>
                      <div class="friend-small-links std-links">
                        <div><%= link_to 'Accept', friendship, method: :put, data: {confirm: 'Are you sure?'} %></div>
                        <div><%= link_to 'Decline', friendship, method: :delete, data: {confirm: 'Are you sure?'} %></div>
                      </div>
                    </div>
                  </div>
              <% end %>
          <% end %>
          <div class="friends-divisory"></div>
          <% if @user.friendships.merge(Friendship.pending).count == 0 %>
              <div class="tab-header">You have not sent any invitations</div>
          <% else %>
              <div class="tab-header"><%= @user.friendships.merge(Friendship.pending).count %> sent invitations</div>
              <% @user.friendships.merge(Friendship.pending).each do |friendship| %>
                  <% friend = User.find(friendship.friend_id) %>
                  <div class="friend-box">
                    <%= link_to(friend, class: "friend-small-image") do %><% end %>
                    <div class="friend-small-info">
                      <%= link_to(friend, class: "friend-name std-link") do %>
                        <%= friend.name %>
                      <% end %>
                      <div><strong><%= friend.activities.count %></strong> activities</div>
                      <div class="friend-small-links std-links">
                        <a class="icon-scratch" id="remove-ownFriendPend-scratch" data-confirm="Are you sure?" data-method="delete" rel="nofollow" href="<%= friendship_path(friendship) %>" title="Remove Friend Request"  style="vertical-align:middle"></a>
                            </div>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="calendar"></div>

app/views/users/edit.html.erb
<div id="box-team-row">
  <div id="box-team-wrapper">
    <h1>Editing user</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @user %>
  </div>
</div>

app/views/users/search.html.erb
<div id="search">
  <%= render :partial => 'users/search_form' %>
</div>
<div class="item-box">
  <% if @users.nil? %>

  <% else %>
      <div style="margin-bottom: 20px">
        <% if @users.count == 1%>1 match
        <% else %>
        <%= @users.count %> matches
        <% end %></div>
      <ul>
        <% @users.each do |user| %>
            <li class="friend-box">
              <%= link_to(user, class: "friend-small-image") %>
              <div class="friend-small-info">
                <%= link_to(user, class: "friend-name std-link") do %>
                    <%= user.name %>
                <% end %>
                <div><strong><%= user.activities.count %></strong> activities</div>
                <div class="friend-small-links std-links">
                </div>
              </div>
            </li>
        <% end %>
      </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="user-page" class="item-box col-md-12">
  <% if @user.id == current_user.id %>
      <%= render 'show_self' %>
  <% else %>
      <%= render 'show_other' %>
  <% end %>
</div>