config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :places
  devise_for :users
  resources :friendships
  get 'users/search' => 'users#search'
  resources :users

  post 'teams/:id/add' => 'teams#addmember'

  get 'teams/:id/add' => 'teams#add'
  get 'users/:user_id/activities' => 'activities#index'
  get 'activities/leaderboards' => 'activities#leaderboards'
  resources :activities

  root 'dashboard#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  enum actype: [ :Swimming, :Running, :Cycling, :Gymn ]

  belongs_to :user
  belongs_to :place

  validates_presence_of :place
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index]
  @@j = ActiveSupport::JSON
  @@descending_sort = ->(a,b) {b.second <=> a.second}

  def index
    @activities = @user.activities.order(date: :desc)
  end

  def show
    @place = @activity.place
    @acattributes = @@j.decode(@activity.acattributes)
  end

  def new
    @activity = Activity.new
  end

  def edit

  end

  def create
    @activity = Activity.new(activity_params)
    attri = ""
    if @activity.Swimming? ||  @activity.Running? || @activity.Cycling? || @activity.Gymn?
      attri = @@j.encode(acattributes)
    end
    @activity.user_id = current_user.id
    placename = params[:activity][:place]
    @place = Place.find_by_name(placename)
    if @place.nil?
      @place = Place.new
      @place.name = placename
      @place.save!
    end
    @activity.place_id = @place.id
    @activity.acattributes = attri
    @activity.save!
    @place.activities << @activity
    current_user.activities << @activity
    @place.save!
    current_user.save!
    redirect_to @activity
  end

  def update
    @activity.update(activity_params)
    attri = ""
    #if @activity.Swimming? ||  @activity.Running? || @activity.Cycling? || @activity.Gymn?
      attri = @@j.encode(acattributes)
    #end
    @activity.acattributes = attri
    @activity.save!
    render 'activities/update'
    redirect_to @activity
  end

  def destroy
    @activity.destroy
    #para tds as actividds
    redirect_to current_user
  end

  def leaderboards
    lglobal = Activity.joins('JOIN friendships').where("friendships.status = 0 AND ((activities.user_id = friendships.user_id AND friendships.friend_id = #{current_user.id}) OR (activities.user_id = friendships.friend_id AND friendships.user_id = #{current_user.id}) OR activities.user_id = #{current_user.id})").uniq
    lswim = Activity.where(actype: 0).joins('JOIN friendships').where("friendships.status = 0 AND ((activities.user_id = friendships.user_id AND friendships.friend_id = #{current_user.id}) OR (activities.user_id = friendships.friend_id AND friendships.user_id = #{current_user.id}) OR activities.user_id = #{current_user.id})").uniq
    lrun = Activity.where(actype: 1).joins('JOIN friendships').where("friendships.status = 0 AND ((activities.user_id = friendships.user_id AND friendships.friend_id = #{current_user.id}) OR (activities.user_id = friendships.friend_id AND friendships.user_id = #{current_user.id}) OR activities.user_id = #{current_user.id})").uniq
    lcycle = Activity.where(actype: 2).joins('JOIN friendships').where("friendships.status = 0 AND ((activities.user_id = friendships.user_id AND friendships.friend_id = #{current_user.id}) OR (activities.user_id = friendships.friend_id AND friendships.user_id = #{current_user.id}) OR activities.user_id = #{current_user.id})").uniq
    lgym = Activity.where(actype: 3).joins('JOIN friendships').where("friendships.status = 0 AND ((activities.user_id = friendships.user_id AND friendships.friend_id = #{current_user.id}) OR (activities.user_id = friendships.friend_id AND friendships.user_id = #{current_user.id}) OR activities.user_id = #{current_user.id})").uniq

    lglobalByFreq = lglobal.group('activities.user_id').count
    @lglobalByFreq = []
    lglobalByFreq.each { |a| @lglobalByFreq << a }
    @lglobalByFreq.sort!(& @@descending_sort)

    lswimByFreq = lswim.group('activities.user_id').count
    @lswimByFreq = []
    lswimByFreq.each { |a| @lswimByFreq << a }
    @lswimByFreq.sort!(& @@descending_sort)

    lrunByFreq = lrun.group('activities.user_id').count
    @lrunByFreq = []
    lrunByFreq.each { |a| @lrunByFreq << a }
    @lrunByFreq.sort!(& @@descending_sort)

    lcycleByFreq = lcycle.group('activities.user_id').count
    @lcycleByFreq = []
    lcycleByFreq.each { |a| @lcycleByFreq << a }
    @lcycleByFreq.sort!(& @@descending_sort)

    lgymByFreq = lgym.group('activities.user_id').count
    @lgymByFreq = []
    lgymByFreq.each { |a| @lgymByFreq << a }
    @lgymByFreq.sort!(& @@descending_sort)
  end

  def listAll

    listAllG = Activity.where("activities.user_id = #{current_user.id}").order(date: :desc)

    #POR SEMANA

    @allactivitiesThisWeek = []
    liAll = listAllG
    liAll.each do |activity|
      if (activity.date.strftime("%W").to_i - DateTime.current.strftime("%W").to_i) == 0
        @allactivitiesThisWeek << activity
      end
    end

    @swimactivitiesThisWeek = []
    lwswim = listAllG.where(actype: 0)
    lwswim.each do |activity|
      if (activity.date.strftime("%W").to_i - DateTime.current.strftime("%W").to_i) == 0
        @swimactivitiesThisWeek << activity
      end
    end

    @runactivitiesThisWeek = []
    lwrun =listAllG.where(actype: 1)
    lwrun.each do |activity|
      if (activity.date.strftime("%W").to_i - DateTime.current.strftime("%W").to_i) == 0
        @runactivitiesThisWeek << activity
      end
    end

    @cycleactivitiesThisWeek = []
    lwcycle = listAllG.where(actype: 2)
    lwcycle.each do |activity|
      if (activity.date.strftime("%W").to_i - DateTime.current.strftime("%W").to_i) == 0
        @cycleactivitiesThisWeek << activity
      end
    end

    @gymactivitiesThisWeek = []
    lwgym = listAllG.where(actype: 3)
    lwgym.each do |activity|
      if (activity.date.strftime("%W").to_i - DateTime.current.strftime("%W").to_i) == 0
        @gymactivitiesThisWeek << activity
      end
    end

   #POR MES

    @allactivitiesThisMonth = []
    lmAll = listAllG
    lmAll.each do |activity|
      if (activity.date.month - DateTime.current.month) == 0
        @allactivitiesThisMonth << activity
      end
    end

    @swimactivitiesThisMonth = []
    lmswim = listAllG.where(actype: 0)
    lmswim.each do |activity|
      if (activity.date.month - DateTime.current.month) == 0
        @swimactivitiesThisMonth << activity
      end
    end

    @runactivitiesThisMonth = []
    lmrun = listAllG.where(actype: 1)
    lmrun.each do |activity|
      if (activity.date.month - DateTime.current.month) == 0
        @runactivitiesThisMonth << activity
      end
    end

    @cycleactivitiesThisMonth = []
    lmcycle = listAllG.where(actype: 2)
    lmcycle.each do |activity|
      if (activity.date.month - DateTime.current.month) == 0
        @cycleactivitiesThisMonth << activity
      end
    end

    @gymactivitiesThisMonth = []
    lmgym = listAllG.where(actype: 3)
    lmgym.each do |activity|
      if (activity.date.month - DateTime.current.month) == 0
        @gymactivitiesThisMonth << activity
      end
    end

    #POR ANO

    @allactivitiesThisYear = []
    lyAll = listAllG
    lyAll.each do |activity|
      if (activity.date.year - DateTime.current.year) == 0
        @allactivitiesThisYear << activity
      end
    end

    @swimactivitiesThisYear = []
    lyswim = listAllG.where(actype: 0)
    lyswim.each do |activity|
      if (activity.date.year - DateTime.current.year) == 0
        @swimactivitiesThisYear << activity
      end
    end

    @runactivitiesThisYear = []
    lyrun =listAllG.where(actype: 1)
    lyrun.each do |activity|
      if (activity.date.year - DateTime.current.year) == 0
        @runactivitiesThisYear << activity
      end
    end

    @cycleactivitiesThisYear = []
    lycycle = listAllG.where(actype: 2)
    lycycle.each do |activity|
      if (activity.date.year - DateTime.current.year) == 0
        @cycleactivitiesThisYear << activity
      end
    end

    @gymactivitiesThisYear= []
    lygym =listAllG.where(actype: 3)
    lygym.each do |activity|
      if (activity.date.year - DateTime.current.year) == 0
        @gymactivitiesThisYear << activity
      end
    end
  end

  private

    def set_user
      if params[:user_id].nil?
        @user = current_user
      else
        @user = User.find(params[:user_id])
      end
    end

    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:date, :duration, :actype, :description)
    end

    def acattributes
      params.permit(:pools, :speed, :distance, :sets, :gpx_data)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_edit.html.erb
<div id="create-activity-popbox" class="popbox">
  <div class="fields-box">
    <h1>Editing activity</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/activities/_form.html.erb
<%= form_for @activity, remote: true do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
   <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration, class: "std-field" %>
  </div>

    <% if params[:action] == 'new' %>
        <div class="field">
          <%= f.label :place %><br>
          <%= f.text_field :place, class: "std-field" %>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description, class: "std-field" %>
    </div>

    <div class="field">
      <%= f.label 'Activity type' %><br>
      <%= f.select :actype, options_for_select(["Swimming", "Running", "Cycling", "Gymn"]) %>
    </div>

    <div class="swimming-fields fields">
      <%= f.label :pools %><br>
      <input id="activity_pools" type="text" name="pools" class="std-field"/>
    </div>

    <div class="cycling-fields running-fields">
      <div class="fields">
          <%= f.label :speed %><br>
        <input id="activity_speed" type="text" name="speed" class="std-field"/>
      </div>
      <div class="fields">
          <%= f.label :distance %><br>
        <input id="activity_distance" type="text" name="distance" class="std-field"/>
      </div>
    </div>

    <div class="gymn-fields fields">
      <%= f.label :sets %><br>
      <input id="activity_sets" type="text" name="sets" class="std-field"/>
    </div>

    <input id="activity-gpx-data" name="gpx_data" type="hidden" value="{}">

  <div class="actions">
    <%= f.submit "Create", class: "std-btn" %>
  </div>
<% end %>

<div class="cycling-fields running-fields">
  <div class="file-browse">
    <input class="browse-button" id="gpx-file" type="file"/>
  </div>
</div>

app/views/activities/_new.html.erb
<div id="create-activity-popbox" class="popbox">
  <div class="fields-box">
    <h1>New activity</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/activities/create.html.erb
<%= params %>

app/views/activities/edit.js.erb
var box = $("#popbox-container");

box.html("<%= escape_javascript(render 'edit') %>").append("<div class='box-backdrop'></div>");
box.fadeIn();
popBoxJS(); //so it detects newly created elements
activitySelectJS();
$('#gpx-file').change(validateGPX);

app/views/activities/index.html.erb
<div class="item-box col-md-12">
  <div class="col-md-12">
    <h3>Activities</h3>
  </div>
  <div class="col-md-12 table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Date</th>
        <th>Duration</th>
        <th>Place</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @activities.each do |activity| %>
          <tr>
            <td><%= activity.date %></td>
            <td><%= activity.duration %> minutes</td>
            <td><%= activity.place.name %></td>
            <td><%= link_to 'Show', activity %></td>
            <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
            <td><%= link_to 'Remove', activity, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <%= link_to 'Create a new Activity', new_activity_path, class: 'std-btn-link' %>
</div>

app/views/activities/index.js.erb
$("#dash-friend-act-display").html("<%= escape_javascript(render partial: 'dashboard/activities_list', locals: { activities: @activities } ) %>");

app/views/activities/leaderboards.html.erb
<!-- ALL ACTIVITIES FREQ -->

<div class="item-box col-md-12">
  <div id="upper-btn-wrap-wrap" class="col-md-12">
    <div id="btn-wrap">
        <div class="std-btn">Frequency</div>
        <div class="std-btn">Duration</div>
    </div>
  </div>
  <div class="col-md-12">
    <h3>All Activities Leaderboard by Freq</h3>
  </div>
  <div class="col-md-12 table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Username</th>
        <th>Frequency</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @lglobalByFreq.each do |pair| %>
      <% @user = User.find(pair.first)%>
          <tr>
            <td><%= @user.name.capitalize %></td>
            <td><%= pair.second %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>
</div>

<!-- SWIM FREQ -->

<div class="item-box col-md-12">
  <div class="col-md-12">
    <h3>Swimming Leaderboard by Freq</h3>
  </div>
  <div class="col-md-12 table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Username</th>
        <th>Frequency</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @lswimByFreq.each do |pair| %>
          <% @user = User.find(pair.first)%>
          <tr>
            <td><%= @user.name.capitalize %></td>
            <td><%= pair.second %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>
</div>

<!-- RUN FREQ -->

<div class="item-box col-md-12">
  <div class="col-md-12">
    <h3>Running Leaderboard by Freq</h3>
  </div>
  <div class="col-md-12 table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Username</th>
        <th>Frequency</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @lrunByFreq.each do |pair| %>
          <% @user = User.find(pair.first)%>
          <tr>
            <td><%= @user.name.capitalize %></td>
            <td><%= pair.second %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>
</div>

<!-- CYCLE FREQ -->

<div class="item-box col-md-12">
  <div class="col-md-12">
    <h3>Cycling Leaderboard by Freq</h3>
  </div>
  <div class="col-md-12 table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Username</th>
        <th>Frequency</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @lcycleByFreq.each do |pair| %>
          <% @user = User.find(pair.first)%>
          <tr>
            <td><%= @user.name.capitalize %></td>
            <td><%= pair.second %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>
</div>

<!-- GYM FREQ -->

<div class="item-box col-md-12">
  <div class="col-md-12">
    <h3>Gymn Leaderboard by Freq</h3>
  </div>
  <div class="col-md-12 table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Username</th>
        <th>Frequency</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @lgymByFreq.each do |pair| %>
          <% @user = User.find(pair.first)%>
          <tr>
            <td><%= @user.name.capitalize %></td>
            <td><%= pair.second %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>
</div>

app/views/activities/new.js.erb
var box = $("#popbox-container");

box.html("<%= escape_javascript(render 'new') %>").append("<div class='box-backdrop'></div>");
box.fadeIn();
popBoxJS(); //so it detects newly created elements
activitySelectJS();
$('#gpx-file').change(validateGPX);

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>
<% adate = @activity.date %>
<h2>
  <%= @activity.actype %>
  at <%= link_to @place.name, @place, class: "std-link" %>
</h2>

<h4>
  <% if (adate - Time.now).to_i/86400 > 7 || (adate - Time.now) < 0 %>
    <%= adate.day %> of <%= adate.strftime("%B") %> <%= adate.year %> by <%= adate.hour.to_s.rjust(2, '0') %>:<%= adate.min.to_s.rjust(2, '0') %>
  <% else %>
    This <%= adate.strftime("%A") %> by <%= adate.hour.to_s.rjust(2, '0') %>:<%= adate.min.to_s.rjust(2, '0') %>
  <% end %>
</h4>

<p>
  <strong>Duration:</strong>
  <% if @activity.duration.nil? %>
    Currently unknown
  <% else %>
    <%= seconds_to_time(@activity.duration) %>
  <% end %>
</p>

<% if @activity.Swimming? %>
    <p>
      <strong>Pools:</strong>
      <% if @acattributes['pools'].nil? || @acattributes['pools'] == 0 || @acattributes['pools'] == '' %>
          Not even one...
      <% else %>
          <%= @acattributes['pools'] %>
      <% end %>
    </p>
<% elsif @activity.Running? || @activity.Cycling? %>
    <p>
      <strong>Speed:</strong>
      <%= @acattributes['speed'] %> Km/h
    </p>
    <p>
      <strong>Distance:</strong>
      <%= @acattributes['distance'] %> meters
    </p>
<% elsif @activity.Gymn? %>
    <p>
      <strong>Sets:</strong>
      <%= @acattributes['sets'] %>
    </p>
<% end %>

<% if @activity.user_id %>
    <%= link_to 'Edit', edit_activity_path(@activity), remote: true %>
<% end %>
<% if @activity.Running? || @activity.Cycling? %>
    <input id="activity-attrs" type="hidden" value='<%= @acattributes.to_json %>'>
    <div id="map-container" class="middle-container">
      <div id="activity-map"></div>
    </div>
<% end %>

app/views/activities/update.js.erb
alert("hey b0ss");