config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :places
  devise_for :users
  resources :friendships
  get 'users/search' => 'users#search'
  resources :users

  post 'teams/:id/add' => 'teams#addmember'

  get 'teams/:id/add' => 'teams#add'
  get 'users/:user_id/activities' => 'activities#index'
  get 'activities/leaderboards' => 'activities#leaderboards'
  resources :activities

  root 'dashboard#index'

end

app/models/place.rb
class Place < ActiveRecord::Base

  has_many :activities
  validates_uniqueness_of :name


end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @places = Place.all

  end

  def show
    @users = User.find_by_sql("SELECT users_at_place.*
      FROM
      (
      SELECT users.*
      FROM users INNER JOIN activities ON (users.id = activities.user_id)
      WHERE activities.place_id = #{@place.id} AND
      (datetime(activities.date, '+' || activities.duration || ' seconds') > datetime('now','utc') OR
       activities.duration IS NULL AND datetime(activities.date) < datetime('now','utc')) AND
      users.id <> #{current_user.id}
      ) AS users_at_place INNER JOIN friendships ON ((users_at_place.id = friendships.friend_id) OR (users_at_place.id = friendships.user_id))
      WHERE friendships.user_id = #{current_user.id} OR friendships.friend_id = #{current_user.id}")
  end

  def new
    @place = Place.new
  end

  def edit
  end

  def create
    @place = Place.new(place_params)
    @place.save!
  end

  def update
    @place.update(place_params)
    redirect_to @place
  end

  def destroy
    @place.destroy
  end

  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:name)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<div id="place-info-container">
  <div id="place-img"></div>
  <h2 id="place-name">
    <%= @place.name %>
  </h2>
  <h4 id="place-description">
    <%= @place.description %>
  </h4>
  <div id="nearby-friends-container">
    <% @users.each do |user| %>
        <div class="team-member">
          <%= link_to(user, class: "member-small-image") do %><% end %>
          <div class="team-member-info">
            <%= link_to(user, class: "member-name std-link") do %>
                <%= user.name %>
            <% end %>
            <div><strong><%= user.activities.count %></strong> activities</div>
            <div class="member-small-links std-links">
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>